import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4001/login?redirect=/');
  await page.getByRole('button', { name: 'Player Registration Register' }).click();
  await page.getByRole('textbox', { name: 'e.g. TKD-2026-ABCD' }).fill('TKD-2026-TEST1');
  await page.getByRole('textbox', { name: 'e.g. TKD-2026-ABCD' }).press('Enter');
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('button', { name: 'Continue To Form' }).click();
  await page.getByRole('button', { name: 'Open Setup' }).click();
  await page.getByRole('dialog', { name: 'Start Player Registration' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('mahesh');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Date of Birth *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Date of Birth *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Date of Birth *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Date of Birth *' }).fill('1998-01-01');
  await page.getByRole('button', { name: 'Male', exact: true }).click();
  await page.getByRole('button', { name: 'Female' }).click();
  await page.getByRole('button', { name: 'Male', exact: true }).click();
  await page.getByRole('textbox', { name: 'Phone Number *' }).click();
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('6300356590');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('mahesh@gmail.com');
  await page.getByRole('textbox', { name: 'Street address, area,' }).click();
  await page.getByRole('textbox', { name: 'Street address, area,' }).fill('vijayawada macavaram');
  await page.getByRole('textbox', { name: 'State' }).click();
  await page.getByRole('textbox', { name: 'State' }).fill('AP');
  await page.getByRole('textbox', { name: 'District' }).click();
  await page.getByRole('textbox', { name: 'District' }).fill('NTR');
  await page.getByRole('textbox', { name: 'District' }).press('Tab');
  await page.getByRole('textbox', { name: 'Pincode' }).fill('520004');
  await page.getByRole('combobox').click();
  await page.getByText('Working / Occupation').click();
  await page.getByRole('combobox').press('ControlOrMeta+-');
  await page.getByRole('combobox').press('ControlOrMeta+-');
  await page.getByRole('combobox').press('ControlOrMeta+-');
  await expect(page.locator('#root')).toMatchAriaSnapshot(`- text: Residential Address`);
  await page.getByRole('textbox', { name: 'Occupation' }).click();
  await page.getByRole('textbox', { name: 'Occupation' }).fill('NAP');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('combobox').click();
  await page.getByText('Black Belt 2nd Dan').click();
  await page.getByText('Belt Color *Black Belt 2nd DanDan ID / Kukkiwon NumberWeight (kg) *Years of').click();
  await page.getByRole('textbox', { name: 'Dan ID / Kukkiwon Number' }).click();
  await page.getByRole('textbox', { name: 'Dan ID / Kukkiwon Number' }).fill('5234789');
  await page.getByRole('spinbutton', { name: 'Weight (kg) *' }).click();
  await page.getByRole('spinbutton', { name: 'Weight (kg) *' }).fill('73');
  await page.getByRole('textbox', { name: 'Years of Experience' }).click();
  await page.getByRole('textbox', { name: 'Years of Experience' }).fill('9');
  await page.getByRole('textbox', { name: 'Coach Name' }).click();
  await page.getByRole('textbox', { name: 'Coach Name' }).fill('mar');
  await page.getByRole('checkbox', { name: 'Poomsae (Individual)' }).click();
  await page.locator('label').filter({ hasText: 'Poomsae Pair' }).click();
  await page.getByRole('checkbox', { name: 'Poomsae Pair' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Secret Key *' }).click();
  await page.getByRole('textbox', { name: 'Secret Key *' }).fill('Lee@1255');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('checkbox', { name: 'I confirm the details above' }).click();
  await page.getByRole('checkbox', { name: 'I confirm the details above' }).press('ControlOrMeta+Shift+I');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Submit Registration' }).click();
  const download = await downloadPromise;
  await page.goto('http://localhost:4001/login?redirect=/');
});